name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liT48yeXh83JR26h"
GITHUB_OWNER = "EVA0M3"
GITHUB_REPO = "my-navsphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsphere-dwz.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://navsphere-dwz.pages.dev"

